language: node_js
node_js:
  - "<%= node.version %>"
before_install:
  - npm install -g grunt-cli istanbul jasmine-node coveralls
script:
  - npm test --verbose
after_success:
  - istanbul cover jasmine-node --captureExceptions ./spec/
  - cat ./coverage/lcov.info | coveralls && rm -rf ./coverage
<% if(travis.deploy) { %>deploy:
  provider: npm
  email: "<%= author.email %>"
  api_key: "<%= travis.apikey %>"
  on:
    branch: master<% } %>
